import {
  MessagesSquare,
  Eye,
  LayoutDashboard,
  FileBarChart,
  Users,
  Settings,
  ScrollText,
  Slash,
  MonitorSmartphone,
  Home,
  Star,
  Bell,
  Inbox,
  Phone,
  Mail,
  Calendar,
  BarChart3,
  PieChart,
  Folder,
  FileText,
  ClipboardList,
  UserCog,
  ShieldCheck,
  Wrench,
  Building2,
  Headphones,
  Layers,
  Grid3x3,
  Tag,
  Bookmark,
  Target,
  TrendingUp,
  Package,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated icon picker for the Landing Page menu editor — reuses lucide-react
 * (already a dependency, no upload/new package needed). Keys are stored in
 * LandingPageSettings.menuItems[to].icon; an unknown/missing key falls back
 * to that item's own default icon from Sidebar's MENU_ITEMS.
 */
export const ICON_LIBRARY: Record<string, LucideIcon> = {
  messagesSquare: MessagesSquare,
  eye: Eye,
  layoutDashboard: LayoutDashboard,
  fileBarChart: FileBarChart,
  users: Users,
  settings: Settings,
  scrollText: ScrollText,
  slash: Slash,
  monitorSmartphone: MonitorSmartphone,
  home: Home,
  star: Star,
  bell: Bell,
  inbox: Inbox,
  phone: Phone,
  mail: Mail,
  calendar: Calendar,
  barChart3: BarChart3,
  pieChart: PieChart,
  folder: Folder,
  fileText: FileText,
  clipboardList: ClipboardList,
  userCog: UserCog,
  shieldCheck: ShieldCheck,
  wrench: Wrench,
  building2: Building2,
  headphones: Headphones,
  layers: Layers,
  grid: Grid3x3,
  tag: Tag,
  bookmark: Bookmark,
  target: Target,
  trendingUp: TrendingUp,
  package: Package,
};
